#ifndef DEFINES_H
#define DEFINES_H

#define TILEROWS 16
#define TILECOLUMNS 16

#define MAXSTATICLEVELS 30
#define MAXUSERLEVELS 1000

#define FPS 30
#define MAXMUSICFILES 25
#define NROFSOUNDS 8

#define SND_MENU 0
#define SND_SELECT 1
#define SND_ERROR 2
#define SND_EXPLODE 3
#define SND_MOVE 4
#define SND_TELEPORT 5
#define SND_LEVELPASS 6
#define SND_LEVELFAIL 7

#define SizeIncrease 0.10

#define NROFBUTTONS 12

#define BUT_UP 0
#define BUT_RIGHT 1
#define BUT_DOWN 2
#define BUT_LEFT 3
#define BUT_A 4
#define BUT_X 5
#define BUT_START 6
#define BUT_SELECT 7
#define BUT_L 8
#define BUT_R 9
#define BUT_VOLMIN 10
#define BUT_VOLUP 11

#define GSLEVELEDITORLEVELSELECT 1 
#define GSGAME 2
#define GSINGAMEMENU 3 
#define GSQUIT 4 
#define GSDIEDMENU 5 
#define GSWINMENU 6 
#define GSLEVELSELECTMENU 7 
#define GSTITLESCREEN 8 
#define GSLEVELTYPESELECT 9 
#define GSLEVELEDITOR 10 
#define GSLEVELEDITORMENU 11 
#define GSINTRO 12
#define GSMOVEPIECEITTER 13
#define GSGETNAME 14
#define GSPRINTMSG 15
#define GSCREDITS 16

#define GSINITDIFF 50

#define GSLEVELEDITORLEVELSELECTINIT GSLEVELEDITORLEVELSELECT + GSINITDIFF
#define GSGAMEINIT GSGAME + GSINITDIFF
#define GSINGAMEMENUINIT GSINGAMEMENU  + GSINITDIFF
#define GSQUITINIT GSQUIT + GSINITDIFF
#define GSDIEDMENUINIT GSDIEDMENU + GSINITDIFF
#define GSWINMENUINIT GSWINMENU + GSINITDIFF
#define GSLEVELSELECTMENUINIT GSLEVELSELECTMENU + GSINITDIFF
#define GSTITLESCREENINIT GSTITLESCREEN + GSINITDIFF
#define GSLEVELTYPESELECTINIT GSLEVELTYPESELECT + GSINITDIFF
#define GSLEVELEDITORINIT GSLEVELEDITOR + GSINITDIFF
#define GSLEVELEDITORMENUINIT GSLEVELEDITORMENU + GSINITDIFF
#define GSINTROINIT GSINTRO + GSINITDIFF
#define GSGETNAMEINIT GSGETNAME + GSINITDIFF
#define GSPRINTMSGINIT GSPRINTMSG + GSINITDIFF
#define GSCREDITSINIT GSCREDITS + GSINITDIFF

const char NameSymbols[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 _-";

#endif
