# Controls when the workflow will run
on:
  # Allows you to run this workflow manually ftarget the Actions tab
  workflow_dispatch:

env:
  ARTIFACT_NAME: Dynamate playdate Html
  

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Playdate SDL2 Api Sources
        uses: actions/checkout@v3
        with:
          repository: 'joyrider3774/Playdate_Api_SDL2'

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          path: emsdk
          repository: 'emscripten-core/emsdk'
          
      - name: Checkout Playdate SDL2 Api Sources
        uses: actions/checkout@v3
        with:
          repository: 'joyrider3774/Playdate_Api_SDL2'
      
      - name: Setup emscripten stuff
        run: |
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest
            source ./emsdk_env.sh
       
      - name: move things to correct directories
        run: |
          rm -rf ./src/srcgame
          mv tmp/src ./src/srcgame
          cp -Rf tmp/Source/. ./Source

      - name: Build Game        
        run: |
          emmake make CPP_BUILD=1 EMSCRIPTEN_BUILD=1

      - name: Store build
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: html
